packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

allowBuilds:
  esbuild: true

catalogMode: prefer
cleanupUnusedCatalogs: true

catalog:
  "@playwright/test": ^1.62.1
  "@tanstack/devtools": 0.15.0
  "@tanstack/history": 1.162.4
  "@tanstack/router-core": 1.171.34
  "@tanstack/start-client-core": 1.170.34
  "@tanstack/start-plugin-core": 1.171.49
  "@tanstack/start-server-core": 1.169.39
  "@tanstack/store": 0.11.2
  postcss: ^8.5.26
  tailwindcss: ^4.3.3
  vite: 8.2.1

catalogs:
  node20:
    "@types/node": ^20.19.43
  node24:
    "@types/node": ^24.13.3

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true

overrides:
  "js-yaml@>=4.0.0 <4.3.2": 4.3.2
  "seroval@>=0.12.0 <1.6.3": 1.6.8
  "source-map-js@>=1.0.0 <1.2.2": 1.2.2

update:
  githubActions: true
