export { createContext, type FigContext } from "./context.ts";
// Data-protocol types referenced by public renderer APIs (root.data,
// createRoot({ initialData }), the server results' getData()). Types only:
// every runtime data API is importable exclusively from @bgub/fig —
// that split is what lets renderer bundles ship without the store
// implementation, and type exports do not weaken it.
export type {
  DataRefreshResult,
  DataResource,
  DataResourceKey,
  DataResourceKeyInput,
  DataResourceLoadContext,
  DataResourceLoader,
  FigDataHydrationEntry,
  FigDataStoreController,
  FigDataStoreHandle,
  FigDataStoreOptions,
} from "./data.ts";
export {
  type DataResourceOptions,
  createDataStore,
  dataResource,
  ensureData,
  invalidateData,
  invalidateDataError,
  invalidateDataKey,
  invalidateDataPrefix,
  readDataStore,
  refreshData,
} from "./data-store.ts";
export {
  Activity,
  type ActivityMode,
  type ActivityProps,
  type AwaitedFigNode,
  type ClientReferenceOptions,
  clientReference,
  type ComponentProps,
  type ComponentType,
  createElement,
  type ElementType,
  ErrorBoundary,
  type ErrorBoundaryProps,
  type ErrorInfo,
  type FigClientReference,
  type FigElement,
  type FigNode,
  type FigPortal,
  type FigViewTransition,
  Fragment,
  isValidElement,
  type Key,
  type LazyLoader,
  lazy,
  type Props,
  Suspense,
  type SuspenseProps,
  ViewTransition,
  type ViewTransitionClass,
  type ViewTransitionProps,
} from "./element.ts";
export {
  createMixin,
  type EmptyMixinValue,
  type MixinContext,
  type MixinDescriptor,
  type MixinFactory,
  type MixinInput,
  type MixinResult,
  type MixinType,
} from "./mixin.ts";
// The data layer: definitions and freshness verbs. The store implementation
// travels with dataResource itself (a factory slot on each resource), so
// bundles that never define a resource never ship the store.
export {
  type ActionStateAction,
  type ActionStateRunner,
  type DependencyList,
  type EffectCallback,
  type ExternalStoreSubscribe,
  preloadData,
  readContext,
  readData,
  readPromise,
  type StartTransition,
  type StateSetter,
  useActionState,
  useBeforeLayout,
  useBeforePaint,
  useCallback,
  useSyncExternalStore,
  useId,
  useDeferredValue,
  useMemo,
  useReactive,
  useStableEvent,
  useState,
  useTransition,
} from "./hooks.ts";
export {
  type AssetResourceBlocking,
  type AssetsProps,
  assets,
  type ClientReferenceAssets,
  type CrossOrigin,
  type FetchPriority,
  type FigAssetResource,
  type FigAssetResourceList,
  type FontResource,
  font,
  type MetaResource,
  type MetaResourceOptions,
  type ModulePreloadResource,
  meta,
  modulepreload,
  type PreconnectResource,
  type PreloadResource,
  preconnect,
  preload,
  type ScriptResource,
  type StylesheetResource,
  script,
  stylesheet,
  type TitleResource,
  title,
} from "./resource.ts";
export { transition } from "./transition.ts";
