export { createContext, type FigContext } from "./context.ts";
export {
  clientReference,
  createElement,
  createElement as h,
  createPortalNode,
  ErrorBoundary,
  Fragment,
  lazy,
  Activity,
  Suspense,
  type ClientReferenceOptions,
  type ElementType,
  type ErrorBoundaryProps,
  type ErrorInfo,
  type FigClientReference,
  type FigElement,
  type FigNode,
  type FigPortal,
  type FigText,
  type Key,
  type LazyLoader,
  type Props,
  type ActivityMode,
  type ActivityProps,
  type SuspenseProps,
} from "./element.ts";
export {
  readContext,
  readPromise,
  useActionState,
  useBeforeLayout,
  useBeforePaint,
  useCallback,
  useExternalStore,
  useId,
  useLaggedValue,
  useMemo,
  useReactive,
  useStableEvent,
  useState,
  useTransition,
  type ActionStateAction,
  type ActionStateRunner,
  type DependencyList,
  type EffectCallback,
  type ExternalStoreSubscribe,
  type StableEventArgs,
  type StateSetter,
  type StartTransition,
} from "./hooks.ts";
export {
  assets,
  font,
  clientReferenceAssets,
  meta,
  modulepreload,
  preconnect,
  preload,
  script,
  stylesheet,
  title,
  type ClientReferenceAssets,
  type CrossOrigin,
  type FetchPriority,
  type FigAssetResource,
  type FigAssetResourceList,
  type FontResource,
  type MetaResource,
  type ModulePreloadResource,
  type PreconnectResource,
  type PreloadResource,
  type AssetResourceBlocking,
  type AssetsOptions,
  type ScriptResource,
  type StylesheetResource,
  type TitleResource,
} from "./resource.ts";
export { transition, type TransitionHandler } from "./transition.ts";
// Data-protocol types referenced by public renderer APIs (root.data,
// createRoot({ initialData }), the server results' getData()). Types only:
// every runtime data API is importable exclusively from @bgub/fig-data —
// that split is what lets renderer bundles ship without the store
// implementation, and type exports do not weaken it.
export type {
  DataRefreshResult,
  DataResourceKey,
  DataResourceKeyInput,
  DataResourceLoadContext,
  FigDataHydrationEntry,
  FigDataResource,
  FigDataStoreHandle,
} from "./data.ts";
